export const FETCH_REQUEST = 'POSTS/FETCH_REQUEST';
export const FETCH_ERROR = 'POSTS/FETCH_ERROR';
export const FETCH_RESPONSE = 'POSTS/FETCH_RESPONSE';
export const CREATE_REQUEST = 'POSTS/CREATE_REQUEST';
export const CREATE_ERROR = 'POSTS/CREATE_ERROR';
export const CREATE_RESPONSE = 'POSTS/CREATE_RESPONSE';
export const CLEAN_POST_ID_REQUEST = 'POSTS/CLEAN_POST_ID_REQUEST';