export const SET_POSTS = 'POSTS/SET_POSTS';
export const SET_TOTAL_POSTS_COUNT = 'POSTS/SET_TOTAL_POSTS_COUNT';
export const FETCH_REQUEST = 'POSTS/FETCH_REQUEST';
export const FETCH_ERROR = 'POSTS/FETCH_ERROR';
export const FETCH_RESPONSE = 'POSTS/FETCH_RESPONSE';