export const FETCH_REQUEST = 'POST/FETCH_REQUEST';
export const FETCH_ERROR = 'POST/FETCH_ERROR';
export const FETCH_RESPONSE = 'POST/FETCH_RESPONSE';
export const DELETE_REQUEST = 'POSTS/DELETE_REQUEST';
export const DELETE_ERROR = 'POSTS/DELETE_ERROR';
export const DELETE_RESPONSE = 'POSTS/DELETE_RESPONSE';
export const CLEAN_POST_ID_REQUEST = 'POSTS/CLEAN_POST_ID_REQUEST';