export const FETCH_REQUEST = 'USER/FETCH_REQUEST';
export const FETCH_ERROR = 'USER/FETCH_ERROR';
export const FETCH_RESPONSE = 'USER/FETCH_RESPONSE';

export const DELETE_REQUEST = 'USER/DELETE_REQUEST';
export const DELETE_ERROR = 'USER/DELETE_ERROR';
export const DELETE_RESPONSE = 'USER/DELETE_RESPONSE';