export const FETCH_REQUEST = 'USERS/FETCH_REQUEST';
export const FETCH_ERROR = 'USERS/FETCH_ERROR';
export const FETCH_RESPONSE = 'USERS/FETCH_RESPONSE';
export const CREATE_REQUEST = 'USERS/CREATE_REQUEST';
export const CREATE_ERROR = 'USERS/CREATE_ERROR';
export const CREATE_RESPONSE = 'USERS/CREATE_RESPONSE';
export const CLEAN_USER_ID_REQUEST = 'USERS/CLEAN_USER_ID_REQUEST';